---
development:
  cloud_name: flickfeeder
  api_key: '823318763549944'
  api_secret: nD3zTOvKrivVjUhFGx6Pxt6aeY4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: flickfeeder
  api_key: '823318763549944'
  api_secret: nD3zTOvKrivVjUhFGx6Pxt6aeY4
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: flickfeeder
  api_key: '823318763549944'
  api_secret: nD3zTOvKrivVjUhFGx6Pxt6aeY4
  enhance_image_tag: true
  static_image_support: false
